### ISSUE TITLE
Define a communication protocol between the computer and the glove

### ISSUE THREAD

**Issue by TStod** [TStod/Capstone#1]
Specifications are up to you but i would try to make it adaptable to specify up to individual pouch pressure and to report each pouches status on each communication. Additionally we should have a set of maintenance commands like turn on pump, set max pressure, set min pressure (tank thresholds). Some of these commands we may turn off after development.

**Comment by neilkdave** [comment]
@TStod Expand protocol to 13 characters for 13 pouches.

**Comment by TStod** [comment]
Closing 

Pull Request: https://github.com/TStod/Capstone/pull/5

New issue for expanding glove protocol: https://github.com/TStod/Capstone/issues/8
